## Suburb API

### Get all suburbs
GET https://localhost:5001/api/suburbs HTTP/1.1

### GET a single suburb
GET https://localhost:5001/api/suburbs/6 HTTP/1.1

### Create a suburb
POST https://localhost:5001/api/suburbs HTTP/1.1
content-type: application/json

{
    "name": "Test Suburb 15",
    "postcode": 1015,
    "stateid": 1
}

### Update a suburb
PUT https://localhost:5001/api/suburbs/3 HTTP/1.1
content-type: application/json

{
    "name": "Burwood",
    "postcode": 2134,
    "stateid": 2
}

### Delete a suburb
DELETE https://localhost:5001/api/suburbs/26 HTTP/1.1