## Owner API

### Get all owners
GET https://localhost:5001/api/owners HTTP/1.1

### GET an owner
GET https://localhost:5001/api/owners/1 HTTP/1.1

### Create an owner
POST https://localhost:5001/api/owners HTTP/1.1
content-type: application/json

{
    "name": "Tester 1",
    "email": "tester1@example.com",
    "mobile": "0441234567"
}

### update an owner
PUT https://localhost:5001/api/owners/9 HTTP/1.1
content-type: application/json

{
    "name": "Tester 11",
    "email": "tester11@example.com",
    "mobile": "0441234569"
}

### Delete an owner
DELETE https://localhost:5001/api/owners/4 HTTP/1.1