## Owner API

### Get all owners
GET https://localhost:5001/api/owners HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### Get all owners sorting by name in ascending order
GET https://localhost:5001/api/owners?sortBy=name&isSortedAscending=true HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### Get all owners sorting by name in descending order
GET https://localhost:5001/api/owners?sortBy=name&isSortedAscending=false HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### Get all owners sorting by email in ascending order
GET https://localhost:5001/api/owners?sortBy=email&isSortedAscending=true HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### Get all owners sorting by email in descending order
GET https://localhost:5001/api/owners?sortBy=email&isSortedAscending=false HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### Get all owners on page 1 and page size is 3
GET https://localhost:5001/api/owners?page=1&pageSize=3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### GET an owner
GET https://localhost:5001/api/owners/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

### Create an owner
POST https://localhost:5001/api/owners HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

{
    "name": "Tester 1",
    "email": "tester1@example.com",
    "mobile": "0441234567"
}

### Update an owner
PUT https://localhost:5001/api/owners/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw

{
    "name": "Tester 1",
    "email": "tester1@example.com",
    "mobile": "0441234561"
}

### Delete an owner
DELETE https://localhost:5001/api/owners/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ik1UQkZPRFZDT1RBMlJEQkROekU1TVRJMU1rTkNSa05HTURCQlJFSTROMFZDTVRSQk9VRTJSZyJ9.eyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20vcm9sZXMiOltdLCJpc3MiOiJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tLyIsInN1YiI6ImF1dGgwfDYwNmRhNjM4NGQ4ZWRkMDA2ODBlMWU4MyIsImF1ZCI6WyJodHRwczovL2FwaS5wcm9wZXJ0eXJlbnRhbC5jb20iLCJodHRwczovL2FidmVnYXByb2plY3QuYXUuYXV0aDAuY29tL3VzZXJpbmZvIl0sImlhdCI6MTYxODY1ODYyNCwiZXhwIjoxNjE4NzQ1MDI0LCJhenAiOiJGY3Fzd1RwZUdTTkF5Z1JBVXRNUUwxS2N4UDl1bHNPUSIsInNjb3BlIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJwZXJtaXNzaW9ucyI6W119.Pvm3Z_SE67Jdhg2rEqGtY7UH648z6fRS3CtzsvyxowhWwF0hZU1x2ljYOi0iPi5_Noc_yatyQOImoz09huj5i9tVqK3_MbjrI_rR-UBNEVvIv6YMHbV1VknKckfx9pQtOVf4ohqMZKFrMYkzQ-b6UX3S34Y1T3_k647_dotY8j9u2kpGvLIneD_5Aszw3Wx7L1Y3gUmRbd6-M4kGeQplDvE5WBI0iCjp1zWEh1lCS09--zzq_teenlzc-jl9BkTn7lAZCcxYZHdHZ6Oj2rZS51blR0cKBUirrK92XhkxuMm2IKJ_dHf81dA8zlswrV1GbI0o9w2McIr49e97LAtciw