## Property API

### Get all properties
GET https://localhost:5001/api/properties HTTP/1.1

### Get all available properties
GET https://localhost:5001/api/properties?available=true HTTP/1.1

### GET a property
GET https://localhost:5001/api/properties/12 HTTP/1.1

### Create a property
POST https://localhost:5001/api/properties HTTP/1.1
content-type: application/json

{
    "unit": "22",
    "street": "44 Kent Street",
    "suburbid": 3,
    "propertytypeid": 1,
    "ownerid": 1,
    "bedroom": 1,
    "bathroom": 1,
    "parking": 0,
    "petsAllowed": true,
    "builtInWardrobe": true,
    "gasAvailable": true,
    "hasStudyRoom": false,
    "available": true,
    "furnished": false
}

### Update a property
PUT https://localhost:5001/api/properties/17 HTTP/1.1
content-type: application/json

{
    "unit": "55",
    "street": "33 Burwodd Rd",
    "suburbid": 4,
    "propertytypeid": 3,
    "ownerid": 3,
    "bedroom": 2,
    "bathroom": 1,
    "parking": 1,
    "petsAllowed": false,
    "builtInWardrobe": true,
    "gasAvailable": true,
    "hasStudyRoom": false,
    "available": false,
    "furnished": false
}

### Delete a property
DELETE https://localhost:5001/api/properties/1 HTTP/1.1