## Rental API

### Get all rentals
GET https://localhost:5001/api/rentals HTTP/1.1

### GET a rental
GET https://localhost:5001/api/rentals/1 HTTP/1.1

### Create a rental
POST https://localhost:5001/api/rentals HTTP/1.1
content-type: application/json

{
    "propertyid": 12,
    "startdate": "2019-01-05",
    "enddate": "2018-10-05",
    "payment": 550,
    "tenantid": 16
}

### Update a rental
PUT https://localhost:5001/api/rentals/7 HTTP/1.1
content-type: application/json

{
    "propertyid": 11,
    "startdate": "2018-01-15",
    "enddate": "2018-10-25",
    "payment": 560,
    "tenantid": 15
}

### Delete a rental
DELETE https://localhost:5001/api/rentals/9 HTTP/1.1