## Rental API

### Get all rentals
GET https://localhost:5001/api/rentals HTTP/1.1

### Get all rentals that is in suburb whose suburbId is 5 (Abbotsford)
GET https://localhost:5001/api/rentals?suburbId=5 HTTP/1.1

### Get all rentals whose stateId is 2 (New South Wales)
GET https://localhost:5001/api/rentals?stateId=2 HTTP/1.1

### Get all rentals whose minimum rent is $400 and maximum rent is $500
GET https://localhost:5001/api/rentals?minimumRent=400&maximumRent=550 HTTP/1.1

### Get all rentals whose start date is 2020-04-01 and start date is 2021-07-30
GET https://localhost:5001/api/rentals?startDate=2020-04-01&endDate=2021-07-30 HTTP/1.1

### Get all rentals sorting by owner in ascending order
GET https://localhost:5001/api/rentals?sortBy=owner&isSortedAscending=true HTTP/1.1

### Get all rentals sorting by owner in descending order
GET https://localhost:5001/api/rentals?sortBy=owner&isSortedAscending=false HTTP/1.1

### Get all rentals sorting by tenant in ascending order
GET https://localhost:5001/api/rentals?sortBy=tenant&isSortedAscending=true HTTP/1.1

### Get all rentals sorting by tenant in descending order
GET https://localhost:5001/api/rentals?sortBy=tenant&isSortedAscending=false HTTP/1.1

### Get all rentals on page 1 and page size is 3
GET https://localhost:5001/api/rentals?page=1&pageSize=3 HTTP/1.1

### GET a rental
GET https://localhost:5001/api/rentals/1 HTTP/1.1

### Create a rental
POST https://localhost:5001/api/rentals HTTP/1.1
content-type: application/json

{
    "propertyid": 12,
    "startdate": "2019-01-05",
    "enddate": "2019-10-05",
    "payment": 500,
    "tenantid": 3
}

### Update a rental
PUT https://localhost:5001/api/rentals/34 HTTP/1.1
content-type: application/json

{
    "propertyid": 12,
    "startdate": "2017-01-15",
    "enddate": "2017-10-25",
    "payment": 560,
    "tenantid": 3
}

### Delete a rental
DELETE https://localhost:5001/api/rentals/15 HTTP/1.1