## Tenant API

### Get all tenants
GET https://localhost:5001/api/tenants HTTP/1.1

### Get all available tenants
GET https://localhost:5001/api/tenants?available=true HTTP/1.1

### Get all tenants sorting by name in ascending order
GET https://localhost:5001/api/tenants?sortBy=name&isSortedAscending=true HTTP/1.1

### Get all tenants sorting by name in descending order
GET https://localhost:5001/api/tenants?sortBy=name&isSortedAscending=false HTTP/1.1

### Get all tenants sorting by email in ascending order
GET https://localhost:5001/api/tenants?sortBy=email&isSortedAscending=true HTTP/1.1

### Get all tenants sorting by email in descending order
GET https://localhost:5001/api/tenants?sortBy=email&isSortedAscending=false HTTP/1.1

### Get all tenants on page 1 and page size is 3
GET https://localhost:5001/api/tenants?page=1&pageSize=3 HTTP/1.1

### Get a tenant
GET https://localhost:5001/api/tenants/1 HTTP/1.1

### Create a tenant
POST https://localhost:5001/api/tenants HTTP/1.1
content-type: application/json

{
    "name": "Test tenant 5",
    "email": "testtenant5@example.com",
    "mobile": "0412345685"
}

### Update a tenant
PUT https://localhost:5001/api/tenants/15 HTTP/1.1
content-type: application/json

{
    "name": "Test tenant 2",
    "email": "testtenant2@example.com",
    "mobile": "0412345672"
}

### Delete a tenant
DELETE https://localhost:5001/api/tenants/8 HTTP/1.1