## Tenant API

### Get all tenants
GET https://localhost:5001/api/tenants HTTP/1.1

### Get a tenant
GET https://localhost:5001/api/tenants/1 HTTP/1.1

### Create a tenant
POST https://localhost:5001/api/tenants HTTP/1.1
content-type: application/json

{
    "name": "Test tenant 5",
    "email": "testtenant5@example.com",
    "mobile": "0412345685"
}

### Update a tenant
PUT https://localhost:5001/api/tenants/15 HTTP/1.1
content-type: application/json

{
    "name": "Test tenant 2",
    "email": "testtenant2@example.com",
    "mobile": "0412345672"
}

### Delete a tenant
DELETE https://localhost:5001/api/tenants/8 HTTP/1.1